services:
  # Layanan Caddy sebagai Reverse Proxy Terpusat
  caddy:
    image: caddy:2-alpine
    container_name: shared-caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
    networks:
      - shared_net

  # Layanan PostgreSQL
  pgsql:
    image: postgres:17.6-alpine3.21
    container_name: shared-pgsql
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_net

  # Layanan Redis
  redis:
    image: redis:alpine
    container_name: shared-redis
    restart: always
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - shared_net

# Jaringan yang akan digunakan oleh semua layanan terpusat
networks:
  shared_net:
    driver: bridge

# Volume untuk persistensi data
volumes:
  pg_data:
